# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: L2 ANALYTICS
email: leolacerdagaller@live.com
description: >- # this means to ignore newlines until "baseurl:"
  Professional insights into data analytics, Spark optimization, and modern data engineering solutions.
  Sharing practical expertise in big data technologies, database management, and performance tuning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leogaller.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: LeoGaller
linkedin_username: leonardo-galler

# Multilingual settings
languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "assets"]

# Language-specific descriptions
description_en: >-
  Professional insights into data analytics, Spark optimization, and modern data engineering solutions.
  Sharing practical expertise in big data technologies, database management, and performance tuning.
description_pt: >-
  Insights profissionais em análise de dados, otimização Spark e soluções modernas de engenharia de dados.
  Compartilhando experiência prática em tecnologias de big data, gerenciamento de banco de dados e ajuste de performance.

# Author information
author:
  name: Leonardo Galler
  email: leolacerdagaller@live.com
  bio: "Data Engineer & Analytics Professional specializing in Apache Spark, MySQL, and cloud technologies"
  bio_pt: "Engenheiro de Dados & Profissional de Analytics especializado em Apache Spark, MySQL e tecnologias em nuvem"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Minima theme settings
minima:
  skin: dark
  social_links:
    github: LeoGaller
    linkedin: leonardo-galler

# Show excerpts on homepage
show_excerpts: true

# Google Analytics
google_analytics: G-PGZQLHCM02

# SEO and social
lang: en_US
timezone: America/Sao_Paulo

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections for multilingual content
collections:
  posts_pt:
    output: true
    permalink: /pt/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
